/**************************************************************************
 * C S 429 system emulator
 * 
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/ 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "instr_pipeline.h"
#include "forward.h"
#include "machine.h"
#include "hw_elts.h"

#define SP_NUM 31
#define XZR_NUM 32

extern machine_t guest;
extern mem_status_t dmem_status;

extern int64_t W_wval;

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally. 
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t 
generate_DXMW_control(opcode_t op, d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs) {
    //d sigs
    D_sigs->src2_sel = (op == OP_STUR);
    //x sigs
    X_sigs->valb_sel = (op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_MVN || op == OP_ORR_RR ||op == OP_ADDS_RR || op == OP_EOR_RR || op == OP_ANDS_RR || op == OP_TST_RR);
    X_sigs->set_CC = (op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_ANDS_RR || op == OP_ADDS_RR || op == OP_TST_RR);
    //m sigs
    M_sigs->dmem_read = (op == OP_LDUR);
    M_sigs->dmem_write = (op == OP_STUR);
    //w sigs
    W_sigs->dst_sel = (op == OP_BL);
    W_sigs->wval_sel = (op == OP_LDUR);
    W_sigs->w_enable = !(op == OP_STUR || op == OP_B || op == OP_B_COND || op == OP_RET || op == OP_NOP || op == OP_HLT);

    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */

static comb_logic_t 
extract_immval(uint32_t insnbits, opcode_t op, int64_t *imm) {
    int constFive = 5;
    int constSix = 6;
    int constTwel = 12;
    int constNin = 9;
    int constNinteen = 19;
    int constTen = 10;
    if (op == OP_STUR || op == OP_LDUR) {
        *imm = bitfield_u32(insnbits, constTwel, constNin);
    }
    else if (op == OP_LDUR){
        *imm = bitfield_u32(insnbits, constTwel, constNin);
    }
    else if (op == OP_ADRP) {
        *imm = (bitfield_u32(insnbits, constFive, constNinteen) << 14) | (bitfield_u32(insnbits, 29, 2) << constTwel);
    }
    else if (op == OP_MOVK) {
        *imm = bitfield_u32(insnbits, constFive, 16);
    }
    else if (op == OP_MOVZ){
        *imm = bitfield_u32(insnbits, constFive, 16);
    }
    else if (op == OP_ADD_RI || op == OP_SUB_RI || op == OP_ASR) {
        *imm = bitfield_u32(insnbits, constTen, constTwel);
    }
    else if (op == OP_SUB_RI) {
        *imm = bitfield_u32(insnbits, constTen, constTwel);
    }
    else if (op == OP_ASR) {
        *imm = bitfield_u32(insnbits, constTen, constTwel);
    }
    else if (op == OP_LSR) {
        *imm = bitfield_u32(insnbits, constTen, constSix);
    }
    else if (op == OP_LSL || op == OP_UBFM) {
        *imm = 64 - bitfield_u32(insnbits, 16, constSix);
    }
    else {
        *imm = 0;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    switch (op) {
        case OP_LDUR:
        case OP_STUR:
        case OP_ADRP:
        case OP_ADD_RI:
        case OP_ADDS_RR:
        case OP_B:
        case OP_BL:
        case OP_B_COND:
            *ALU_op = PLUS_OP;
            break;
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
            *ALU_op = MINUS_OP;
            break;
        case OP_MOVK:
        case OP_MOVZ:
        case OP_MVN:
            *ALU_op = MOV_OP;
            break;
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;

        case OP_ANDS_RR:
        case OP_TST_RR:
            *ALU_op = AND_OP;
            break;
                case OP_ASR:
            *ALU_op = ASR_OP;
            break;
        case OP_LSL:
        case OP_UBFM:
            *ALU_op = LSL_OP;
            break;

        case OP_LSR:
            *ALU_op = LSR_OP;
            break;
        default:
            *ALU_op = PLUS_OP;        
    }
    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

comb_logic_t 
copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    dest->dmem_read = src->dmem_read;
    dest->dmem_write = src->dmem_write;
    return;
}

comb_logic_t 
copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    dest->dst_sel = src->dst_sel;
    dest->w_enable = src->w_enable;
    dest->wval_sel = src->wval_sel;
    return;
}

comb_logic_t
extract_regs(uint32_t insnbits, opcode_t op, uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    // printf("GOT OPCODE: %d", op);
    int constFive = 5;
    int constZero = 0;
    int constThirSiz = 36;
    int consSixt = 16;
    switch (op) {
        case OP_LDUR:
            *dst = bitfield_u32(insnbits, constZero, constFive);
            *src1 = bitfield_u32(insnbits, constFive, constFive);
            *src2 = constThirSiz;
            break;
        case OP_STUR:
            *dst = bitfield_u32(insnbits, constZero, constFive);
            *src1 = bitfield_u32(insnbits, constFive, constFive);
            *src2 = constThirSiz;
            break;
            break;
        case OP_MOVK:
        case OP_MOVZ:
        case OP_ADRP:
            *src1 = insnbits & 0x1FU;
            *src2 = constThirSiz;
            *dst = insnbits & 0x1FU;
            break;
        case OP_ADD_RI:
        case OP_SUB_RI:
        case OP_LSL:
        case OP_LSR:
        case OP_UBFM:
        case OP_ASR:
            *dst = bitfield_u32(insnbits, constZero, constFive);
            *src1 = bitfield_u32(insnbits, constFive, constFive);
            *src2 = constThirSiz;
            break;
        case OP_MVN:
            *dst = insnbits & 0x1FU;
            *src2 = bitfield_u32(insnbits, consSixt, constFive) == (constThirSiz-5) ? constThirSiz : bitfield_u32(insnbits, 16, constFive);
            *src1 = constThirSiz;
            break;
        case OP_CMP_RR:
        case OP_TST_RR:
            *dst = 0x20U;
            *src2 = (insnbits & 0x1F0000U) >> consSixt;
            *src1 = (insnbits & 0x3E0U) >> constFive;
            break;
        case OP_SUBS_RR:
        case OP_ADDS_RR:
        case OP_ORR_RR:
        case OP_EOR_RR:
        case OP_ANDS_RR:
            *dst = insnbits & 0x1FU ;
            *src2 = (insnbits & 0x1F0000U) >> consSixt;
            *src1 = (insnbits & 0x3E0U) >> constFive == (constThirSiz-5) ? constThirSiz : (insnbits & 0x3E0U) >> constFive;
            break;
        case OP_RET:
            *src1 =  bitfield_u32(insnbits, constFive, constFive);
            *dst = constThirSiz;
            *src2 = constThirSiz;
            break;
    }
    return;
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 * 
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 * Additionally, make sure the register file is updated
 * with W_out's output when you call it in this stage.
 * 
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {

    
    // Copy input values to output
    out->status = in->status;
    out->op = in->op;
    out->print_op = in->print_op;
    out->cond = bitfield_u32(in->insnbits, 0, 4);
    out->seq_succ_PC = in->seq_succ_PC;
    

    d_ctl_sigs_t * dsigs = malloc(sizeof(d_ctl_sigs_t));

    decide_alu_op(in->print_op, &out->ALU_op);

    generate_DXMW_control(in->print_op, dsigs, &(out->X_sigs), &(out->M_sigs), &(out->W_sigs));
    // Allocate memory for source and destination registers
    uint8_t *src1 = calloc(1,1);
    uint8_t *src2= calloc(1,1);
    uint8_t *dst= calloc(1,1);

    extract_regs(in->insnbits, in->print_op, src1, src2, dst);
    printf("SRC1: %d\t SRC2: %d\t DST: %d\n", *src1, *src2, *dst);
    extract_immval(in->insnbits, in->print_op, &(out->val_imm));
    
    // Check if the operation is either OP_MOVK or OP_MOVZ, set out->val_hw to bits 21 to 22 if true
    if (in->print_op == OP_MOVK) {
    out->val_hw = bitfield_u32(in->insnbits, 21, 2);
    }
    else if (in->print_op == OP_MOVZ){
    out->val_hw = bitfield_u32(in->insnbits, 21, 2);
    }
    else {
    out->val_hw = 0;
    }
    

    out->dst = *dst;
    if (in->print_op == OP_RET) {
        regfile(*dst, *src1, W_out->dst, W_wval, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);
        if (out->val_a == 0) {
            out->val_a = out->val_b; 
            out->val_b = 0;
        }
    }
    else if (in->print_op == OP_STUR) {
        regfile(*src1, *dst, W_out->dst, W_wval, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);
    }
    else {
        regfile(*src1, *src2, W_out->dst, W_wval, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);
    }

    if (in->print_op != OP_STUR) {
        forward_reg(*src1, *src2, X_out->dst, M_out->dst, W_out->dst, M_in->val_ex, 
        W_in->val_ex, W_in->val_mem, W_out->val_ex, W_out->val_mem, 
        M_out->W_sigs.wval_sel, W_out->W_sigs.wval_sel, X_out->W_sigs.w_enable, M_out->W_sigs.w_enable, W_out->W_sigs.w_enable,
        &out->val_a, &out->val_b);
    }
    else {
        forward_reg(*src1, *dst, X_out->dst, M_out->dst, W_out->dst, M_in->val_ex, 
        W_in->val_ex, W_in->val_mem, W_out->val_ex, W_out->val_mem, 
        M_out->W_sigs.wval_sel, W_out->W_sigs.wval_sel, X_out->W_sigs.w_enable, M_out->W_sigs.w_enable, W_out->W_sigs.w_enable,
        &out->val_a, &out->val_b);
    }
    return;
}
